### ISSUE TITLE
Error: Unexpected server response: 429

### ISSUE THREAD

**Issue by jtbutcher** [ronny3050/phone-notification-mirror#22]
When a notification comes in or is cleared from the phone the following error is thrown multiple times:

```
Whoops! There was an uncaught exception...
Error: Unexpected server response: 429
    at ClientRequest.req.on (/home/<redacted>/MagicMirror/modules/phone_notification/node_modules/ws/lib/websocket.js:590:5)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onread (net.js:598:20)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```

This appears to be due to the pushbullet api rate limiting https://docs.pushbullet.com/#ratelimiting

**Comment by ndom91** [comment]
I can confirm I get the Pushpullet API Rate limit error as well, although superficially everything still seems to work, so I'm not sure which requests are being blocked/dropped exactly. Apparently at least only unimportant ones..
